#!/bin/bash

# Docker Testing Patterns - Mini Kanban Project
# This script captures the patterns learned during integration testing

echo "=== Docker Testing Patterns - Mini Kanban Project ==="
echo ""

echo "## 1. Health Check Implementation"
echo "Problem: Backend service health checks failed because curl wasn't installed"
echo "Solution: Use Python instead of curl for health checks"
echo ""
echo "```yaml"
echo "# docker-compose.yml"
echo "backend:"
echo "  healthcheck:"
echo "    test: [\"CMD\", \"python\", \"-c\", \"import requests; requests.get('http://localhost:8000/health', timeout=5)\"]"
echo "    interval: 10s"
echo "    timeout: 5s"
echo "    retries: 3"
echo "    start_period: 30s"
echo "```"
echo ""

echo "## 2. Test Container Build Context"
echo "Problem: Test service couldn't find backend files"
echo "Solution: Use proper build context and copy files"
echo ""
echo "```yaml"
echo "# docker-compose.yml"
echo "test:"
echo "  build:"
echo "    context: ."
echo "    dockerfile: backend/Dockerfile"
echo "  environment:"
echo "    - DATABASE_URL=postgresql://user:password@postgres:5432/minikanban"
echo "    - PYTHONPATH=/app"
echo "  depends_on:"
echo "    postgres:"
echo "      condition: service_healthy"
echo "    backend:"
echo "      condition: service_started"
echo "```"
echo ""

echo "## 3. Integration Test Configuration"
echo "Problem: Tests couldn't connect to PostgreSQL database"
echo "Solution: Use separate conftest.py for integration tests"
echo ""
echo "```python"
echo "# backend/tests/integration/conftest.py"
echo "import pytest"
echo "import os"
echo "from sqlalchemy import create_engine"
echo "from sqlalchemy.orm import sessionmaker"
echo "from app.database import Base"
echo ""
echo "# Configure database URL for tests"
echo "os.environ[\"DATABASE_URL\"] = \"postgresql://user:password@postgres:5432/minikanban\""
echo ""
echo "@pytest.fixture(scope=\"session\")"
echo "def db_engine():"
echo "    engine = create_engine(os.environ[\"DATABASE_URL\"])"
echo "    Base.metadata.create_all(bind=engine)"
echo "    yield engine"
echo "    Base.metadata.drop_all(bind=engine)"
echo ""
echo "@pytest.fixture"
echo "def db_session(db_engine):"
echo "    Session = sessionmaker(bind=db_engine)"
echo "    session = Session()"
echo "    yield session"
echo "    session.close()"
echo "```"
echo ""

echo "## 4. Unique Test Data Generation"
echo "Problem: Tests failed due to duplicate user emails"
echo "Solution: Use UUIDs for unique test data"
echo ""
echo "```python"
echo "# backend/tests/integration/test_integration.py"
echo "import pytest"
echo "import uuid"
echo ""
echo "def test_user_registration_and_authentication_flow(api_client):"
echo "    \"\"\"Test user registration and authentication flow\"\"\""
echo "    # Register a new user with unique email"
echo "    user_data = {"
echo "        \"email\": f\"test-{uuid.uuid4()}@example.com\","
echo "        \"password\": \"testpass123\","
echo "        \"name\": \"Test User\""
echo "    }"
echo "    "
echo "    response = api_client.post(\"/auth/register\", json=user_data)"
echo "    assert response.status_code == 200"
echo "    assert response.json()[\"email\"] == user_data[\"email\"]"
echo "```"
echo ""

echo "## 5. Service Communication"
echo "Problem: Test containers couldn't reach backend services"
echo "Solution: Use service names instead of localhost"
echo ""
echo "```python"
echo "# backend/tests/integration/test_integration.py"
echo "import requests"
echo ""
echo "# Use service name instead of localhost"
echo "response = requests.get(\"http://backend:8000/health\")"
echo "```"
echo ""

echo "## 6. Test Isolation"
echo "Problem: Tests interfered with each other due to shared state"
echo "Solution: Use separate conftest.py and unique data"
echo ""
echo "```python"
echo "# backend/tests/integration/conftest.py"
echo "import pytest"
echo "import requests"
echo "import time"
echo ""
echo "@pytest.fixture(scope=\"session\")"
echo "def wait_for_backend():"
echo "    \"\"\"Wait for backend service to be healthy\"\"\""
echo "    max_attempts = 30"
echo "    attempt = 0"
echo "    "
echo "    while attempt < max_attempts:"
echo "        try:"
echo "            response = requests.get(\"http://backend:8000/health\", timeout=5)"
echo "            if response.status_code == 200:"
echo "                print(\"Backend is healthy\")"
echo "                return"
echo "        except Exception:"
echo "            pass"
echo "        "
echo "        attempt += 1"
echo "        time.sleep(2)"
echo "        print(f\"Waiting for backend... attempt {attempt}/{max_attempts}\")"
echo "    "
echo "    raise Exception(\"Backend service did not become healthy\")"
echo "```"
echo ""

echo "## Key Lessons Learned"
echo ""
echo "### 1. Health Check Implementation"
echo "- Always check what tools are available in containers"
echo "- Use Python instead of curl when curl isn't available"
echo "- Set appropriate timeout and retry values"
echo "- Use `start_period` for services that take time to initialize"
echo ""
echo "### 2. Build Context Management"
echo "- Use proper build context that includes all necessary files"
echo "- Copy files to correct locations in containers"
echo "- Use absolute paths in Dockerfiles"
echo ""
echo "### 3. Test Data Management"
echo "- Use UUIDs to ensure test data uniqueness"
echo "- Avoid hard-coded test data that can cause conflicts"
echo "- Clean up test data after each test"
echo ""
echo "### 4. Service Communication"
echo "- Use service names instead of localhost in Docker networks"
echo "- Ensure proper networking between services"
echo "- Test service connectivity before running tests"
echo ""
echo "### 5. Test Isolation"
echo "- Use separate conftest.py files for different test types"
echo "- Isolate integration tests from unit tests"
echo "- Use proper fixtures for test setup and teardown"
echo ""
echo "## Common Pitfalls"
echo ""
echo "### 1. Health Check Failures"
echo "- **Issue**: Services report unhealthy when they're actually working"
echo "- **Fix**: Use appropriate health check commands and timeouts"
echo "- **Example**: Use Python instead of curl when curl isn't available"
echo ""
echo "### 2. Build Context Issues"
echo "- **Issue**: Test containers can't find required files"
echo "- **Fix**: Use proper build context and file copying"
echo "- **Example**: Copy backend files to test container"
echo ""
echo "### 3. Network Connectivity"
echo "- **Issue**: Test containers can't reach backend services"
echo "- **Fix**: Use service names and proper networking"
echo "- **Example**: Use `http://backend:8000` instead of `http://localhost:8000`"
echo ""
echo "### 4. Test Data Conflicts"
echo "- **Issue**: Tests fail due to duplicate data"
echo "- **Fix**: Use unique test data with UUIDs"
echo "- **Example**: Generate unique emails for each test"
echo ""
echo "### 5. Service Dependencies"
echo "- **Issue**: Tests run before services are ready"
echo "- **Fix**: Use proper dependency management and health checks"
echo "- **Example**: Wait for backend service to be healthy before running tests"
echo ""
echo "## Best Practices"
echo ""
echo "### 1. Service Health Monitoring"
echo "- Implement health checks for all services"
echo "- Wait for services to be healthy before running tests"
echo "- Monitor service logs for debugging"
echo "- Use proper timeout values for health checks"
echo ""
echo "### 2. Test Environment Setup"
echo "- Use separate test environment files"
echo "- Configure database URLs for test environments"
echo "- Use proper service names and networking"
echo "- Ensure all dependencies are available"
echo ""
echo "### 3. Test Data Management"
echo "- Use UUIDs for unique test data"
echo "- Clean up test data after each test"
echo "- Use fixtures for test data setup"
echo "- Avoid hard-coded test data"
echo ""
echo "### 4. Build Optimization"
echo "- Use multi-stage builds for test images"
echo "- Keep test containers minimal and focused"
echo "- Cache dependencies between test runs"
echo "- Use lightweight base images"
echo ""
echo "### 5. Error Handling"
echo "- Implement proper error handling in tests"
echo "- Use try-catch blocks for network requests"
echo "- Log errors for debugging"
echo "- Implement retry logic for flaky tests"
echo ""
echo "## Implementation Checklist"
echo ""
echo "### For New Docker Testing Projects"
echo ""
echo "1. [ ] Create test environment file (`.env.test`)"
echo "2. [ ] Add test services to `docker-compose.yml`"
echo "3. [ ] Implement health checks for all services"
echo "4. [ ] Create test-specific Dockerfiles"
echo "5. [ ] Set up integration test fixtures"
echo "6. [ ] Use unique test data generation"
echo "7. [ ] Implement service communication patterns"
echo "8. [ ] Create Makefile targets for test execution"
echo "9. [ ] Add test documentation"
echo "10. [ ] Set up CI/CD pipeline for automated testing"
echo ""
echo "### For Existing Projects"
echo ""
echo "1. [ ] Audit existing test setup for Docker compatibility"
echo "2. [ ] Fix any health check issues"
echo "3. [ ] Ensure proper build context"
echo "4. [ ] Implement unique test data generation"
echo "5. [ ] Add service health monitoring"
echo "6. [ ] Document testing patterns"
echo "7. [ ] Create reference files for future debugging"
echo ""
echo "=== End of Docker Testing Patterns ==="