# Generated by Django 5.2.17 on 2026-09-05 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. Name of the household.', max_length=100, verbose_name='Household Name')),
                ('week_start_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, help_text='The day of the week when the weekly rotation starts.', verbose_name='Week Start Day')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the household was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the household was last updated.', verbose_name='Updated At')),
                ('admin', models.ForeignKey(help_text='Required. The user who manages this household.', on_delete=django.db.models.deletion.CASCADE, related_name='admin_households', to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
            ],
            options={
                'verbose_name': 'Household',
                'verbose_name_plural': 'Households',
                'db_table': 'households',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('member', 'Member')], default='member', help_text='The role of this user in the household.', max_length=10, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active.', verbose_name='Is Active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user joined this household.', verbose_name='Joined At')),
                ('left_at', models.DateTimeField(blank=True, help_text='Timestamp when the user left this household (if applicable).', null=True, verbose_name='Left At')),
                ('household', models.ForeignKey(help_text='Required. The household this user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.household', verbose_name='Household')),
                ('user', models.ForeignKey(help_text='Required. The user who is a member of this household.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'db_table': 'memberships',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'household')},
            },
        ),
    ]
